kohana.lo: /home/zhuzx/source/kohanaforext/kohana.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zhuzx/source/kohanaforext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zhuzx/source/kohanaforext/kohana.c -o kohana.lo 
$(phplibdir)/kohana.la: ./kohana.la
	$(LIBTOOL) --mode=install cp ./kohana.la $(phplibdir)

./kohana.la: $(shared_objects_kohana) $(KOHANA_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_kohana) $(KOHANA_SHARED_LIBADD)

